##Default settings
server:
  port: 8080
spring:
  jooq:
    sql-dialect: Postgres
  jackson:
    serialization:
      writeDatesAsTimestamps: false
    defaultPropertyInclusion: always

axon:
  eventhandling:
    processors:
      "[org.fennel.users.query]":
        mode: tracking
        source: eventBus

logging:
  level:
    org:
      jooq: 
        Constants: OFF

---
##Development settings
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=fennel,extensions
    username: postgres
    password: developer
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      indent_output: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      jooq: 
        ##tools: debug
        Constants: OFF
      ##axon: debug
    primrose: debug
management:
  endpoints:
    web:
      expose: "*"
    

---
##Test settings
spring:
  profiles: test

---
##Production settings
spring:
  profiles: prod
